/** Türkiye'nin 81 ili (plaka kodu sırasıyla). Seed ve istemci tarafından kullanılır. */
export const CITIES = [
  { plate: 1, name: 'Adana', slug: 'adana' },
  { plate: 2, name: 'Adıyaman', slug: 'adiyaman' },
  { plate: 3, name: 'Afyonkarahisar', slug: 'afyonkarahisar' },
  { plate: 4, name: 'Ağrı', slug: 'agri' },
  { plate: 5, name: 'Amasya', slug: 'amasya' },
  { plate: 6, name: 'Ankara', slug: 'ankara' },
  { plate: 7, name: 'Antalya', slug: 'antalya' },
  { plate: 8, name: 'Artvin', slug: 'artvin' },
  { plate: 9, name: 'Aydın', slug: 'aydin' },
  { plate: 10, name: 'Balıkesir', slug: 'balikesir' },
  { plate: 11, name: 'Bilecik', slug: 'bilecik' },
  { plate: 12, name: 'Bingöl', slug: 'bingol' },
  { plate: 13, name: 'Bitlis', slug: 'bitlis' },
  { plate: 14, name: 'Bolu', slug: 'bolu' },
  { plate: 15, name: 'Burdur', slug: 'burdur' },
  { plate: 16, name: 'Bursa', slug: 'bursa' },
  { plate: 17, name: 'Çanakkale', slug: 'canakkale' },
  { plate: 18, name: 'Çankırı', slug: 'cankiri' },
  { plate: 19, name: 'Çorum', slug: 'corum' },
  { plate: 20, name: 'Denizli', slug: 'denizli' },
  { plate: 21, name: 'Diyarbakır', slug: 'diyarbakir' },
  { plate: 22, name: 'Edirne', slug: 'edirne' },
  { plate: 23, name: 'Elazığ', slug: 'elazig' },
  { plate: 24, name: 'Erzincan', slug: 'erzincan' },
  { plate: 25, name: 'Erzurum', slug: 'erzurum' },
  { plate: 26, name: 'Eskişehir', slug: 'eskisehir' },
  { plate: 27, name: 'Gaziantep', slug: 'gaziantep' },
  { plate: 28, name: 'Giresun', slug: 'giresun' },
  { plate: 29, name: 'Gümüşhane', slug: 'gumushane' },
  { plate: 30, name: 'Hakkari', slug: 'hakkari' },
  { plate: 31, name: 'Hatay', slug: 'hatay' },
  { plate: 32, name: 'Isparta', slug: 'isparta' },
  { plate: 33, name: 'Mersin', slug: 'mersin' },
  { plate: 34, name: 'İstanbul', slug: 'istanbul' },
  { plate: 35, name: 'İzmir', slug: 'izmir' },
  { plate: 36, name: 'Kars', slug: 'kars' },
  { plate: 37, name: 'Kastamonu', slug: 'kastamonu' },
  { plate: 38, name: 'Kayseri', slug: 'kayseri' },
  { plate: 39, name: 'Kırklareli', slug: 'kirklareli' },
  { plate: 40, name: 'Kırşehir', slug: 'kirsehir' },
  { plate: 41, name: 'Kocaeli', slug: 'kocaeli' },
  { plate: 42, name: 'Konya', slug: 'konya' },
  { plate: 43, name: 'Kütahya', slug: 'kutahya' },
  { plate: 44, name: 'Malatya', slug: 'malatya' },
  { plate: 45, name: 'Manisa', slug: 'manisa' },
  { plate: 46, name: 'Kahramanmaraş', slug: 'kahramanmaras' },
  { plate: 47, name: 'Mardin', slug: 'mardin' },
  { plate: 48, name: 'Muğla', slug: 'mugla' },
  { plate: 49, name: 'Muş', slug: 'mus' },
  { plate: 50, name: 'Nevşehir', slug: 'nevsehir' },
  { plate: 51, name: 'Niğde', slug: 'nigde' },
  { plate: 52, name: 'Ordu', slug: 'ordu' },
  { plate: 53, name: 'Rize', slug: 'rize' },
  { plate: 54, name: 'Sakarya', slug: 'sakarya' },
  { plate: 55, name: 'Samsun', slug: 'samsun' },
  { plate: 56, name: 'Siirt', slug: 'siirt' },
  { plate: 57, name: 'Sinop', slug: 'sinop' },
  { plate: 58, name: 'Sivas', slug: 'sivas' },
  { plate: 59, name: 'Tekirdağ', slug: 'tekirdag' },
  { plate: 60, name: 'Tokat', slug: 'tokat' },
  { plate: 61, name: 'Trabzon', slug: 'trabzon' },
  { plate: 62, name: 'Tunceli', slug: 'tunceli' },
  { plate: 63, name: 'Şanlıurfa', slug: 'sanliurfa' },
  { plate: 64, name: 'Uşak', slug: 'usak' },
  { plate: 65, name: 'Van', slug: 'van' },
  { plate: 66, name: 'Yozgat', slug: 'yozgat' },
  { plate: 67, name: 'Zonguldak', slug: 'zonguldak' },
  { plate: 68, name: 'Aksaray', slug: 'aksaray' },
  { plate: 69, name: 'Bayburt', slug: 'bayburt' },
  { plate: 70, name: 'Karaman', slug: 'karaman' },
  { plate: 71, name: 'Kırıkkale', slug: 'kirikkale' },
  { plate: 72, name: 'Batman', slug: 'batman' },
  { plate: 73, name: 'Şırnak', slug: 'sirnak' },
  { plate: 74, name: 'Bartın', slug: 'bartin' },
  { plate: 75, name: 'Ardahan', slug: 'ardahan' },
  { plate: 76, name: 'Iğdır', slug: 'igdir' },
  { plate: 77, name: 'Yalova', slug: 'yalova' },
  { plate: 78, name: 'Karabük', slug: 'karabuk' },
  { plate: 79, name: 'Kilis', slug: 'kilis' },
  { plate: 80, name: 'Osmaniye', slug: 'osmaniye' },
  { plate: 81, name: 'Düzce', slug: 'duzce' },
] as const;

export type CityDef = (typeof CITIES)[number];

/** Salon sayısı çok olan iller listede öne alınır. */
export const FEATURED_CITY_PLATES = [34, 6, 35, 16, 7, 1, 42, 41, 27, 55] as const;

export function cityByPlate(plate: number) {
  return CITIES.find((c) => c.plate === plate);
}
