export const CATALOG_SEED: { name: string; category: 'hot_drink' | 'cold_drink' | 'food' | 'snack' | 'other' }[] = [
  { name: 'Çay', category: 'hot_drink' },
  { name: 'Fincan çay', category: 'hot_drink' },
  { name: 'Türk kahvesi', category: 'hot_drink' },
  { name: 'Nescafe', category: 'hot_drink' },
  { name: 'Filtre kahve', category: 'hot_drink' },
  { name: 'Sıcak çikolata', category: 'hot_drink' },
  { name: 'Bitki çayı', category: 'hot_drink' },
  { name: 'Su', category: 'cold_drink' },
  { name: 'Maden suyu', category: 'cold_drink' },
  { name: 'Kola', category: 'cold_drink' },
  { name: 'Gazoz', category: 'cold_drink' },
  { name: 'Ayran', category: 'cold_drink' },
  { name: 'Meyve suyu', category: 'cold_drink' },
  { name: 'Soğuk çay', category: 'cold_drink' },
  { name: 'Enerji içeceği', category: 'cold_drink' },
  { name: 'Kaşarlı tost', category: 'food' },
  { name: 'Karışık tost', category: 'food' },
  { name: 'Sucuklu tost', category: 'food' },
  { name: 'Hamburger', category: 'food' },
  { name: 'Patates kızartması', category: 'food' },
  { name: 'Cips', category: 'snack' },
  { name: 'Çekirdek', category: 'snack' },
  { name: 'Kuruyemiş', category: 'snack' },
  { name: 'Çikolata', category: 'snack' },
  { name: 'Bisküvi', category: 'snack' },
  { name: 'Istaka tebeşiri', category: 'other' },
  { name: 'Bilardo eldiveni', category: 'other' },
];
